/* Generated by Yosys 0.42+15 (git sha1 74a1dd99a, g++ 14.1.1 -Os) */

module mult(clk, rst, a, b, p);
  wire _000_;
  wire [17:0] _001_;
  wire [5:0] _002_;
  wire _003_;
  wire _004_;
  wire [23:0] _005_;
  input [17:0] a;
  wire [17:0] a;
  wire [17:0] a_i;
  input [5:0] b;
  wire [5:0] b;
  wire [5:0] b_i;
  input clk;
  wire clk;
  output [23:0] p;
  wire [23:0] p;
  wire [23:0] p_i;
  input rst;
  wire rst;
  CC_BUFG _006_ (
    .I(_000_),
    .O(_003_)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h1),
    .SR_VAL(1'h0)
  ) _007_ (
    .CLK(_003_),
    .D(_001_[0]),
    .EN(1'h1),
    .Q(a_i[0]),
    .SR(_004_)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h1),
    .SR_VAL(1'h0)
  ) _008_ (
    .CLK(_003_),
    .D(_001_[1]),
    .EN(1'h1),
    .Q(a_i[1]),
    .SR(_004_)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h1),
    .SR_VAL(1'h0)
  ) _009_ (
    .CLK(_003_),
    .D(_001_[2]),
    .EN(1'h1),
    .Q(a_i[2]),
    .SR(_004_)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h1),
    .SR_VAL(1'h0)
  ) _010_ (
    .CLK(_003_),
    .D(_001_[3]),
    .EN(1'h1),
    .Q(a_i[3]),
    .SR(_004_)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h1),
    .SR_VAL(1'h0)
  ) _011_ (
    .CLK(_003_),
    .D(_001_[4]),
    .EN(1'h1),
    .Q(a_i[4]),
    .SR(_004_)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h1),
    .SR_VAL(1'h0)
  ) _012_ (
    .CLK(_003_),
    .D(_001_[5]),
    .EN(1'h1),
    .Q(a_i[5]),
    .SR(_004_)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h1),
    .SR_VAL(1'h0)
  ) _013_ (
    .CLK(_003_),
    .D(_001_[6]),
    .EN(1'h1),
    .Q(a_i[6]),
    .SR(_004_)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h1),
    .SR_VAL(1'h0)
  ) _014_ (
    .CLK(_003_),
    .D(_001_[7]),
    .EN(1'h1),
    .Q(a_i[7]),
    .SR(_004_)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h1),
    .SR_VAL(1'h0)
  ) _015_ (
    .CLK(_003_),
    .D(_001_[8]),
    .EN(1'h1),
    .Q(a_i[8]),
    .SR(_004_)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h1),
    .SR_VAL(1'h0)
  ) _016_ (
    .CLK(_003_),
    .D(_001_[9]),
    .EN(1'h1),
    .Q(a_i[9]),
    .SR(_004_)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h1),
    .SR_VAL(1'h0)
  ) _017_ (
    .CLK(_003_),
    .D(_001_[10]),
    .EN(1'h1),
    .Q(a_i[10]),
    .SR(_004_)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h1),
    .SR_VAL(1'h0)
  ) _018_ (
    .CLK(_003_),
    .D(_001_[11]),
    .EN(1'h1),
    .Q(a_i[11]),
    .SR(_004_)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h1),
    .SR_VAL(1'h0)
  ) _019_ (
    .CLK(_003_),
    .D(_001_[12]),
    .EN(1'h1),
    .Q(a_i[12]),
    .SR(_004_)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h1),
    .SR_VAL(1'h0)
  ) _020_ (
    .CLK(_003_),
    .D(_001_[13]),
    .EN(1'h1),
    .Q(a_i[13]),
    .SR(_004_)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h1),
    .SR_VAL(1'h0)
  ) _021_ (
    .CLK(_003_),
    .D(_001_[14]),
    .EN(1'h1),
    .Q(a_i[14]),
    .SR(_004_)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h1),
    .SR_VAL(1'h0)
  ) _022_ (
    .CLK(_003_),
    .D(_001_[15]),
    .EN(1'h1),
    .Q(a_i[15]),
    .SR(_004_)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h1),
    .SR_VAL(1'h0)
  ) _023_ (
    .CLK(_003_),
    .D(_001_[16]),
    .EN(1'h1),
    .Q(a_i[16]),
    .SR(_004_)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h1),
    .SR_VAL(1'h0)
  ) _024_ (
    .CLK(_003_),
    .D(_001_[17]),
    .EN(1'h1),
    .Q(a_i[17]),
    .SR(_004_)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h1),
    .SR_VAL(1'h0)
  ) _025_ (
    .CLK(_003_),
    .D(_002_[0]),
    .EN(1'h1),
    .Q(b_i[0]),
    .SR(_004_)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h1),
    .SR_VAL(1'h0)
  ) _026_ (
    .CLK(_003_),
    .D(_002_[1]),
    .EN(1'h1),
    .Q(b_i[1]),
    .SR(_004_)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h1),
    .SR_VAL(1'h0)
  ) _027_ (
    .CLK(_003_),
    .D(_002_[2]),
    .EN(1'h1),
    .Q(b_i[2]),
    .SR(_004_)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h1),
    .SR_VAL(1'h0)
  ) _028_ (
    .CLK(_003_),
    .D(_002_[3]),
    .EN(1'h1),
    .Q(b_i[3]),
    .SR(_004_)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h1),
    .SR_VAL(1'h0)
  ) _029_ (
    .CLK(_003_),
    .D(_002_[4]),
    .EN(1'h1),
    .Q(b_i[4]),
    .SR(_004_)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h1),
    .SR_VAL(1'h0)
  ) _030_ (
    .CLK(_003_),
    .D(_002_[5]),
    .EN(1'h1),
    .Q(b_i[5]),
    .SR(_004_)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h1),
    .SR_VAL(1'h0)
  ) _031_ (
    .CLK(_003_),
    .D(_005_[0]),
    .EN(1'h1),
    .Q(p_i[0]),
    .SR(_004_)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h1),
    .SR_VAL(1'h0)
  ) _032_ (
    .CLK(_003_),
    .D(_005_[1]),
    .EN(1'h1),
    .Q(p_i[1]),
    .SR(_004_)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h1),
    .SR_VAL(1'h0)
  ) _033_ (
    .CLK(_003_),
    .D(_005_[2]),
    .EN(1'h1),
    .Q(p_i[2]),
    .SR(_004_)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h1),
    .SR_VAL(1'h0)
  ) _034_ (
    .CLK(_003_),
    .D(_005_[3]),
    .EN(1'h1),
    .Q(p_i[3]),
    .SR(_004_)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h1),
    .SR_VAL(1'h0)
  ) _035_ (
    .CLK(_003_),
    .D(_005_[4]),
    .EN(1'h1),
    .Q(p_i[4]),
    .SR(_004_)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h1),
    .SR_VAL(1'h0)
  ) _036_ (
    .CLK(_003_),
    .D(_005_[5]),
    .EN(1'h1),
    .Q(p_i[5]),
    .SR(_004_)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h1),
    .SR_VAL(1'h0)
  ) _037_ (
    .CLK(_003_),
    .D(_005_[6]),
    .EN(1'h1),
    .Q(p_i[6]),
    .SR(_004_)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h1),
    .SR_VAL(1'h0)
  ) _038_ (
    .CLK(_003_),
    .D(_005_[7]),
    .EN(1'h1),
    .Q(p_i[7]),
    .SR(_004_)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h1),
    .SR_VAL(1'h0)
  ) _039_ (
    .CLK(_003_),
    .D(_005_[8]),
    .EN(1'h1),
    .Q(p_i[8]),
    .SR(_004_)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h1),
    .SR_VAL(1'h0)
  ) _040_ (
    .CLK(_003_),
    .D(_005_[9]),
    .EN(1'h1),
    .Q(p_i[9]),
    .SR(_004_)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h1),
    .SR_VAL(1'h0)
  ) _041_ (
    .CLK(_003_),
    .D(_005_[10]),
    .EN(1'h1),
    .Q(p_i[10]),
    .SR(_004_)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h1),
    .SR_VAL(1'h0)
  ) _042_ (
    .CLK(_003_),
    .D(_005_[11]),
    .EN(1'h1),
    .Q(p_i[11]),
    .SR(_004_)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h1),
    .SR_VAL(1'h0)
  ) _043_ (
    .CLK(_003_),
    .D(_005_[12]),
    .EN(1'h1),
    .Q(p_i[12]),
    .SR(_004_)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h1),
    .SR_VAL(1'h0)
  ) _044_ (
    .CLK(_003_),
    .D(_005_[13]),
    .EN(1'h1),
    .Q(p_i[13]),
    .SR(_004_)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h1),
    .SR_VAL(1'h0)
  ) _045_ (
    .CLK(_003_),
    .D(_005_[14]),
    .EN(1'h1),
    .Q(p_i[14]),
    .SR(_004_)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h1),
    .SR_VAL(1'h0)
  ) _046_ (
    .CLK(_003_),
    .D(_005_[15]),
    .EN(1'h1),
    .Q(p_i[15]),
    .SR(_004_)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h1),
    .SR_VAL(1'h0)
  ) _047_ (
    .CLK(_003_),
    .D(_005_[16]),
    .EN(1'h1),
    .Q(p_i[16]),
    .SR(_004_)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h1),
    .SR_VAL(1'h0)
  ) _048_ (
    .CLK(_003_),
    .D(_005_[17]),
    .EN(1'h1),
    .Q(p_i[17]),
    .SR(_004_)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h1),
    .SR_VAL(1'h0)
  ) _049_ (
    .CLK(_003_),
    .D(_005_[18]),
    .EN(1'h1),
    .Q(p_i[18]),
    .SR(_004_)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h1),
    .SR_VAL(1'h0)
  ) _050_ (
    .CLK(_003_),
    .D(_005_[19]),
    .EN(1'h1),
    .Q(p_i[19]),
    .SR(_004_)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h1),
    .SR_VAL(1'h0)
  ) _051_ (
    .CLK(_003_),
    .D(_005_[20]),
    .EN(1'h1),
    .Q(p_i[20]),
    .SR(_004_)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h1),
    .SR_VAL(1'h0)
  ) _052_ (
    .CLK(_003_),
    .D(_005_[21]),
    .EN(1'h1),
    .Q(p_i[21]),
    .SR(_004_)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h1),
    .SR_VAL(1'h0)
  ) _053_ (
    .CLK(_003_),
    .D(_005_[22]),
    .EN(1'h1),
    .Q(p_i[22]),
    .SR(_004_)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h1),
    .SR_VAL(1'h0)
  ) _054_ (
    .CLK(_003_),
    .D(_005_[23]),
    .EN(1'h1),
    .Q(p_i[23]),
    .SR(_004_)
  );
  CC_IBUF _055_ (
    .I(a[0]),
    .Y(_001_[0])
  );
  CC_IBUF _056_ (
    .I(a[1]),
    .Y(_001_[1])
  );
  CC_IBUF _057_ (
    .I(a[10]),
    .Y(_001_[10])
  );
  CC_IBUF _058_ (
    .I(a[11]),
    .Y(_001_[11])
  );
  CC_IBUF _059_ (
    .I(a[12]),
    .Y(_001_[12])
  );
  CC_IBUF _060_ (
    .I(a[13]),
    .Y(_001_[13])
  );
  CC_IBUF _061_ (
    .I(a[14]),
    .Y(_001_[14])
  );
  CC_IBUF _062_ (
    .I(a[15]),
    .Y(_001_[15])
  );
  CC_IBUF _063_ (
    .I(a[16]),
    .Y(_001_[16])
  );
  CC_IBUF _064_ (
    .I(a[17]),
    .Y(_001_[17])
  );
  CC_IBUF _065_ (
    .I(a[2]),
    .Y(_001_[2])
  );
  CC_IBUF _066_ (
    .I(a[3]),
    .Y(_001_[3])
  );
  CC_IBUF _067_ (
    .I(a[4]),
    .Y(_001_[4])
  );
  CC_IBUF _068_ (
    .I(a[5]),
    .Y(_001_[5])
  );
  CC_IBUF _069_ (
    .I(a[6]),
    .Y(_001_[6])
  );
  CC_IBUF _070_ (
    .I(a[7]),
    .Y(_001_[7])
  );
  CC_IBUF _071_ (
    .I(a[8]),
    .Y(_001_[8])
  );
  CC_IBUF _072_ (
    .I(a[9]),
    .Y(_001_[9])
  );
  CC_IBUF _073_ (
    .I(b[0]),
    .Y(_002_[0])
  );
  CC_IBUF _074_ (
    .I(b[1]),
    .Y(_002_[1])
  );
  CC_IBUF _075_ (
    .I(b[2]),
    .Y(_002_[2])
  );
  CC_IBUF _076_ (
    .I(b[3]),
    .Y(_002_[3])
  );
  CC_IBUF _077_ (
    .I(b[4]),
    .Y(_002_[4])
  );
  CC_IBUF _078_ (
    .I(b[5]),
    .Y(_002_[5])
  );
  CC_IBUF _079_ (
    .I(clk),
    .Y(_000_)
  );
  CC_OBUF _080_ (
    .A(p_i[0]),
    .O(p[0])
  );
  CC_OBUF _081_ (
    .A(p_i[1]),
    .O(p[1])
  );
  CC_OBUF _082_ (
    .A(p_i[10]),
    .O(p[10])
  );
  CC_OBUF _083_ (
    .A(p_i[11]),
    .O(p[11])
  );
  CC_OBUF _084_ (
    .A(p_i[12]),
    .O(p[12])
  );
  CC_OBUF _085_ (
    .A(p_i[13]),
    .O(p[13])
  );
  CC_OBUF _086_ (
    .A(p_i[14]),
    .O(p[14])
  );
  CC_OBUF _087_ (
    .A(p_i[15]),
    .O(p[15])
  );
  CC_OBUF _088_ (
    .A(p_i[16]),
    .O(p[16])
  );
  CC_OBUF _089_ (
    .A(p_i[17]),
    .O(p[17])
  );
  CC_OBUF _090_ (
    .A(p_i[18]),
    .O(p[18])
  );
  CC_OBUF _091_ (
    .A(p_i[19]),
    .O(p[19])
  );
  CC_OBUF _092_ (
    .A(p_i[2]),
    .O(p[2])
  );
  CC_OBUF _093_ (
    .A(p_i[20]),
    .O(p[20])
  );
  CC_OBUF _094_ (
    .A(p_i[21]),
    .O(p[21])
  );
  CC_OBUF _095_ (
    .A(p_i[22]),
    .O(p[22])
  );
  CC_OBUF _096_ (
    .A(p_i[23]),
    .O(p[23])
  );
  CC_OBUF _097_ (
    .A(p_i[3]),
    .O(p[3])
  );
  CC_OBUF _098_ (
    .A(p_i[4]),
    .O(p[4])
  );
  CC_OBUF _099_ (
    .A(p_i[5]),
    .O(p[5])
  );
  CC_OBUF _100_ (
    .A(p_i[6]),
    .O(p[6])
  );
  CC_OBUF _101_ (
    .A(p_i[7]),
    .O(p[7])
  );
  CC_OBUF _102_ (
    .A(p_i[8]),
    .O(p[8])
  );
  CC_OBUF _103_ (
    .A(p_i[9]),
    .O(p[9])
  );
  CC_IBUF _104_ (
    .I(rst),
    .Y(_004_)
  );
  CC_MULT #(
    .A_WIDTH(32'd18),
    .B_WIDTH(32'd6),
    .P_WIDTH(32'd24)
  ) \7  (
    .A(a_i),
    .B(b_i),
    .P(_005_)
  );
endmodule
