/* Generated by Yosys 0.42+15 (git sha1 74a1dd99a, g++ 14.1.1 -Os) */

module top(externalClk, resetBtn, enableSw, manualClocking, debugMode, programmingMode, manualClk, rx, tx, sevenSegmentLEDs, sevenSegmentAnodes);
  wire _00_;
  wire \addressdecoder_inst.clk ;
  wire \cpu_core_inst.cu.hardwarereset ;
  wire \cpu_core_inst.cu.programmingmode ;
  input debugMode;
  wire debugMode;
  input enableSw;
  wire enableSw;
  input externalClk;
  wire externalClk;
  input manualClk;
  wire manualClk;
  input manualClocking;
  wire manualClocking;
  wire \memorymapping_inst.debugmode ;
  wire \memorymapping_inst.manualclk ;
  wire \memorymapping_inst.manualclocking ;
  wire \memorymapping_inst.rx ;
  input programmingMode;
  wire programmingMode;
  input resetBtn;
  wire resetBtn;
  input rx;
  wire rx;
  output [3:0] sevenSegmentAnodes;
  wire [3:0] sevenSegmentAnodes;
  output [6:0] sevenSegmentLEDs;
  wire [6:0] sevenSegmentLEDs;
  output tx;
  wire tx;
  CC_IBUF _01_ (
    .I(debugMode),
    .Y(\memorymapping_inst.debugmode )
  );
  CC_IBUF _02_ (
    .I(enableSw),
    .Y(_00_)
  );
  CC_IBUF _03_ (
    .I(externalClk),
    .Y(\addressdecoder_inst.clk )
  );
  CC_IBUF _04_ (
    .I(manualClk),
    .Y(\memorymapping_inst.manualclk )
  );
  CC_IBUF _05_ (
    .I(manualClocking),
    .Y(\memorymapping_inst.manualclocking )
  );
  CC_IBUF _06_ (
    .I(programmingMode),
    .Y(\cpu_core_inst.cu.programmingmode )
  );
  CC_IBUF _07_ (
    .I(resetBtn),
    .Y(\cpu_core_inst.cu.hardwarereset )
  );
  CC_IBUF _08_ (
    .I(rx),
    .Y(\memorymapping_inst.rx )
  );
  CC_OBUF _09_ (
    .A(1'h1),
    .O(sevenSegmentAnodes[0])
  );
  CC_OBUF _10_ (
    .A(1'h1),
    .O(sevenSegmentAnodes[1])
  );
  CC_OBUF _11_ (
    .A(1'h1),
    .O(sevenSegmentAnodes[2])
  );
  CC_OBUF _12_ (
    .A(1'h1),
    .O(sevenSegmentAnodes[3])
  );
  CC_OBUF _13_ (
    .A(1'h0),
    .O(sevenSegmentLEDs[0])
  );
  CC_OBUF _14_ (
    .A(1'h0),
    .O(sevenSegmentLEDs[1])
  );
  CC_OBUF _15_ (
    .A(1'h0),
    .O(sevenSegmentLEDs[2])
  );
  CC_OBUF _16_ (
    .A(1'h0),
    .O(sevenSegmentLEDs[3])
  );
  CC_OBUF _17_ (
    .A(1'h0),
    .O(sevenSegmentLEDs[4])
  );
  CC_OBUF _18_ (
    .A(1'h0),
    .O(sevenSegmentLEDs[5])
  );
  CC_OBUF _19_ (
    .A(1'h1),
    .O(sevenSegmentLEDs[6])
  );
  CC_OBUF _20_ (
    .A(1'h1),
    .O(tx)
  );
endmodule
